package _05_horoscope;

import javax.swing.JOptionPane;

public class HOROSCOPE {
public static void main(String[] args) {
String zs=JOptionPane.showInputDialog(null, "WHAT IS YOUR ZODIAC SIGN MY CHILD!?!?!?");
if (zs.equalsIgnoreCase("Aquarius")) {
	JOptionPane.showMessageDialog(null, "You are...Forward thinking, communicative, people oriented, stubborn, generous, and dedicated. "
			+ "Downside... If this sign does not have alone time and time to do much desired reflection, they become dour, emotionless, and even are prone to depressive interludes. They can become highly resentful if they believe that their voice is not being truly heard or valued. Because they do self-reflect, this sign can become quite eccentric in some of the hobbies that they pursue, or activities they enjoy. "
			+ "Upside...Aquarians are among the friendliest of the signs, making friends everywhere. They are often chosen among co-workers and family for special awards and honors because of their ability to network. Highly intelligent they are energetic and talented, often using their abilities to help others. Despite their extensive people skills, they often crave alone time to reflect and think about things. Meditation is recommended for this sign as it helps to maintain that sense of alone time, while at the same time a feeling of connectedness with something greater than themselves. "
			+ "HOROSCOPE...When others are amazed at your achievements today use it as motivation to keep going forward. Others around you are amazed and impressed by what you have achieved lately and what you continue to achieve. Take this praise and compliment thankfully and use it as motivation to keep going. You may feel doubtful sometimes on your journey but know that you are doing great and you deserve all the success you get. Turn the praise into fuel and forge ahead.");	
}else if (zs.equalsIgnoreCase("Scorpio")) {
	JOptionPane.showMessageDialog(null, "You are...Passionate, exacting, loves extremes, combative, reflective. "
			+ "Downside... Scorpio invented the term ‘vendetta’. Once a Scorpio is crossed, they don’t forget it. Female Scorpio are worse about this than they others, often going decades without making amends with friends and family. Scorpio also tend to be pessimistic, often seeing threats where there aren’t any, which can make them suspicious, stubborn and paranoid without cause. "
			+ "Upside...Scorpio exhibit extreme self-control in many areas, and as a result expect that of those around them. They are disciplined, protective and are very interested in others. They give of themselves but do expect the same in return. Scorpio males and females both need to be the leaders, and excel at problem solving and troubleshooting projects and situations. "
			+ "HOROSCOPE...Balance your life today, pay attention to responsibilities and then enjoy having some fun. If you can successfully prioritise today you can balance your life just right. Pay attention to your responsibilities first, get your work done, and then you can have that downtime you so crave. There could even be an overlap in this and you may meet someone important for your career while you are socialising. Grab opportunities and keep striving.");
}else if (zs.equalsIgnoreCase("Aries")) {
	JOptionPane.showMessageDialog(null,"You are...Courageous, energetic, willful, commanding, leading. Often leads when following would be best course of action. Downside...Aries have tunnel vision when working on a project which can make them seem selfish. They can become impatient with those who are not similar to themselves temperamentally and intellectually. The dedication to a project can become stubbornness, possessiveness, and can lead to a withdrawn and sullen attitude. Many Aries who do not feel acknowledged for their accomplishments become sarcastic and rude. Upside...Highly energetic, and has no problem working long hours on a single project. Often take the initiative experiencing new breakthroughs and discoveries. Aries are thorough, painstaking, and have a knack for precise records and clarity. They live hard, love hard, and play hard. HOROSCOPE... Keep an optimistic and positive attitude today and you will have the view point to reach happiness. Your attitude to the day in front of you and everything that comes along in it, is going to mean everything today. Your approach and your mental energy will determine how you perceive things, so do your best to keep positive about things, as how you perceive things will directly determine how happy you are with the way your day turns out. Keep an optimistic view point. ");
}else if (zs.equalsIgnoreCase("Leo")) {
	JOptionPane.showMessageDialog(null, "You are...Generous, organized, protective, beautiful. Downside...Leo have a great sense of self-worth which can cross the line into arrogance. Leo can tend toward extravagance if they are not satisfied with what they have. Because they like to be in charge, they can often become smothering to their mates and friends, which may leave them alone (which Leo hates). Divorce and loss are devastating to this sign as they are all about the community and family. Upside...Leo tend to be honest and decent people, opting to do the right thing regardless of the situation. They love organization so that they can find their ‘things’. Leos love material goods and luxury and want those that they love to experience this wealth as well. Leo are generally accepting of everyone initially and make decent, lasting relationships. HOROSCOPE...Leo tend to be honest and decent people, opting to do the right thing regardless of the situation. They love organization so that they can find their ‘things’. Leos love material goods and luxury and want those that they love to experience this wealth as well. Leo are generally accepting of everyone initially and make decent, lasting relationships.");
}else if (zs.equalsIgnoreCase("Taurus")) {
	JOptionPane.showMessageDialog(null, "You are...Pleasure seeking, loves control, dependable, grounded, provokes slowly, and highly sensual in nature. Downside...Taurus can be stubborn and ‘bullish’ about ideas that they’ve adopted, which can also make them difficult to get along with when attempting to cooperate on a shared project. Taurus needs to be the leader and to be held in high esteem. If they are not, they refuse to work, often finding small ways to sabotage projects, relationships, or undermine authority that they deem unworthy of leadership. Upside...Taurus people almost always finish what they start. They are deliberate thinkers and when making decisions usually make the right one. Taurus are generally adaptable, adjusting easily to new circumstances especially if there is the reward of luxury, comfort, or sensual reward. This sign loves to laugh and spend time with family. HOROSCOPE...You will be pulled in different directions regarding a decision you have to make today, take time out alone to think. The decision you have to make today is a difficult one and you will feel pulled in different directions, one minute you think you know which way to go and then you are pulled the other way. This is going to undermine your confidence in your abilities and in yourself perhaps. If you need some time out by yourself to think, take it and consult with your heart.");
}else if (zs.equalsIgnoreCase("Sagittarius")) {
	JOptionPane.showMessageDialog(null, "You are... Happy, absent minded, creative, adventurous. Downside...Confining a Sagittarian and not allowing for ample space to roam will make this sign rude, and uncooperative. Sagittarians often come up with unrealistic, big plans, but lack the ability to follow through with them. This isn’t because they aren’t capable, but rather they can become sidetracked chasing another avenue of adventure or thought. Sagittarians are about the bigger picture and details often bog them down and bore them. Confining a Sagittarian and not allowing for ample space to roam will make this sign rude, and uncooperative. Sagittarians often come up with unrealistic, big plans, but lack the ability to follow through with them. This isn’t because they aren’t capable, but rather they can become sidetracked chasing another avenue of adventure or thought. Sagittarians are about the bigger picture and details often bog them down and bore them. HOROSCOPE...Today you need to focus on healing yourself emotionally, Sagittarius. It's been tough lately and you deserve a break. Get away from it all or plan your escape. After a few days of dealing with your inner emotions and deep feelings, today you need to relax a little. You feel emotionally drained right now and a break will help you to refocus and build your strength back up. If you can take the day off and get away from it all that would be perfect, but if this is not possible make sure you get plenty of down time and maybe start looking at plans for a holiday or trip you can take soon.");
}





 



}
}
