package _05_horoscope;

import javax.swing.JOptionPane;

public class HOROSCOPE {
public static void main(String[] args) {
String zs=JOptionPane.showInputDialog(null, "WHAT IS YOUR ZODIAC SIGN MY CHILD!?!?!?");
if (zs.equalsIgnoreCase("Aquarius")) {
	JOptionPane.showMessageDialog(null, "You are...Forward thinking, communicative, people oriented, stubborn, generous, and dedicated. Downside... If this sign does not have alone time and time to do much desired reflection, they become dour, emotionless, and even are prone to depressive interludes. They can become highly resentful if they believe that their voice is not being truly heard or valued. Because they do self-reflect, this sign can become quite eccentric in some of the hobbies that they pursue, or activities they enjoy. \n Upside...Aquarians are among the friendliest of the signs, making friends everywhere. They are often chosen among co-workers and family for special awards and honors because of their ability to network. Highly intelligent they are energetic and talented, often using their abilities to help others. Despite their extensive people skills, they often crave alone time to reflect and think about things. Meditation is recommended for this sign as it helps to maintain that sense of alone time, while at the same time a feeling of connectedness with something greater than themselves. \n HOROSCOPE...When others are amazed at your achievements today use it as motivation to keep going forward. Others around you are amazed and impressed by what you have achieved lately and what you continue to achieve. Take this praise and compliment thankfully and use it as motivation to keep going. You may feel doubtful sometimes on your journey but know that you are doing great and you deserve all the success you get. Turn the praise into fuel and forge ahead.");	
}else if (zs.equalsIgnoreCase("Scorpio")) {
	JOptionPane.showMessageDialog(null, "You are...Passionate, exacting, loves extremes, combative, reflective. Downside... Scorpio invented the term ‘vendetta’. Once a Scorpio is crossed, they don’t forget it. Female Scorpio are worse about this than they others, often going decades without making amends with friends and family. Scorpio also tend to be pessimistic, often seeing threats where there aren’t any, which can make them suspicious, stubborn and paranoid without cause. \n Upside...Scorpio exhibit extreme self-control in many areas, and as a result expect that of those around them. They are disciplined, protective and are very interested in others. They give of themselves but do expect the same in return. Scorpio males and females both need to be the leaders, and excel at problem solving and troubleshooting projects and situations. \n HOROSCOPE...Balance your life today, pay attention to responsibilities and then enjoy having some fun. If you can successfully prioritise today you can balance your life just right. Pay attention to your responsibilities first, get your work done, and then you can have that downtime you so crave. There could even be an overlap in this and you may meet someone important for your career while you are socialising. Grab opportunities and keep striving.");
}else if (zs.equalsIgnoreCase("Aries")) {
	JOptionPane.showMessageDialog(null,"You are...Courageous, energetic, willful, commanding, leading. Often leads when following would be best course of action. Downside...Aries have tunnel vision when working on a project which can make them seem selfish. They can become impatient with those who are not similar to themselves temperamentally and intellectually. The dedication to a project can become stubbornness, possessiveness, and can lead to a withdrawn and sullen attitude. Many Aries who do not feel acknowledged for their accomplishments become sarcastic and rude. \n Upside...Highly energetic, and has no problem working long hours on a single project. Often take the initiative experiencing new breakthroughs and discoveries. Aries are thorough, painstaking, and have a knack for precise records and clarity. They live hard, love hard, and play hard. HOROSCOPE... Keep an optimistic and positive attitude today and you will have the view point to reach happiness. Your attitude to the day in front of you and everything that comes along in it, is going to mean everything today. Your approach and your mental energy will determine how you perceive things, so do your best to keep positive about things, as how you perceive things will directly determine how happy you are with the way your day turns out. Keep an optimistic view point. ");
}else if (zs.equalsIgnoreCase("Leo")) {
	JOptionPane.showMessageDialog(null, "You are...Generous, organized, protective, beautiful. Downside...Leo have a great sense of self-worth which can cross the line into arrogance. Leo can tend toward extravagance if they are not satisfied with what they have. Because they like to be in charge, they can often become smothering to their mates and friends, which may leave them alone (which Leo hates). Divorce and loss are devastating to this sign as they are all about the community and family. \n Upside...Leo tend to be honest and decent people, opting to do the right thing regardless of the situation. They love organization so that they can find their ‘things’. Leos love material goods and luxury and want those that they love to experience this wealth as well. Leo are generally accepting of everyone initially and make decent, lasting relationships. HOROSCOPE...Leo tend to be honest and decent people, opting to do the right thing regardless of the situation. They love organization so that they can find their ‘things’. Leos love material goods and luxury and want those that they love to experience this wealth as well. Leo are generally accepting of everyone initially and make decent, lasting relationships.");
}else if (zs.equalsIgnoreCase("Taurus")) {
	JOptionPane.showMessageDialog(null, "You are...Pleasure seeking, loves control, dependable, grounded, provokes slowly, and highly sensual in nature. Downside...Taurus can be stubborn and ‘bullish’ about ideas that they’ve adopted, which can also make them difficult to get along with when attempting to cooperate on a shared project. Taurus needs to be the leader and to be held in high esteem. If they are not, they refuse to work, often finding small ways to sabotage projects, relationships, or undermine authority that they deem unworthy of leadership. \n Upside...Taurus people almost always finish what they start. They are deliberate thinkers and when making decisions usually make the right one. Taurus are generally adaptable, adjusting easily to new circumstances especially if there is the reward of luxury, comfort, or sensual reward. This sign loves to laugh and spend time with family. \n HOROSCOPE...You will be pulled in different directions regarding a decision you have to make today, take time out alone to think. The decision you have to make today is a difficult one and you will feel pulled in different directions, one minute you think you know which way to go and then you are pulled the other way. This is going to undermine your confidence in your abilities and in yourself perhaps. If you need some time out by yourself to think, take it and consult with your heart.");
}else if (zs.equalsIgnoreCase("Sagittarius")) {
	JOptionPane.showMessageDialog(null, "You are... Happy, absent minded, creative, adventurous. Downside...Confining a Sagittarian and not allowing for ample space to roam will make this sign rude, and uncooperative. Sagittarians often come up with unrealistic, big plans, but lack the ability to follow through with them. This isn’t because they aren’t capable, but rather they can become sidetracked chasing another avenue of adventure or thought. Sagittarians are about the bigger picture and details often bog them down and bore them. Confining a Sagittarian and not allowing for ample space to roam will make this sign rude, and uncooperative. Sagittarians often come up with unrealistic, big plans, but lack the ability to follow through with them. This isn’t because they aren’t capable, but rather they can become sidetracked chasing another avenue of adventure or thought. Sagittarians are about the bigger picture and details often bog them down and bore them. \n HOROSCOPE...Today you need to focus on healing yourself emotionally, Sagittarius. It's been tough lately and you deserve a break. Get away from it all or plan your escape. After a few days of dealing with your inner emotions and deep feelings, today you need to relax a little. You feel emotionally drained right now and a break will help you to refocus and build your strength back up. If you can take the day off and get away from it all that would be perfect, but if this is not possible make sure you get plenty of down time and maybe start looking at plans for a holiday or trip you can take soon.");
}else if (zs.equalsIgnoreCase("Capricorn")) {
	JOptionPane.showMessageDialog(null, "You are...Timeless, driven, calculating, ambitious. Downside... Because they are so dedicated to the big picture and the minute details, they can seem dull to others, who don’t understand the active internal nature of the Capricorn. While seeming almost emotionless on the surface, the Capricorn’s mind is always running on overdrive. They can often seem selfish and stingy, keeping information to themselves, or strategically withholding information for their own gain. Often they can be the less imaginative of the signs and refuse to face the facts about a situation because it would signal that they were wrong about something (which they hate).Capricorns are the superheroes when It comes to making realistic, logical decisions. Their ability to cut through the red tape and see the bottom line is what makes them a real asset to any relationship or occupation where teamwork is valued. \n Upside...Capricorn are family oriented, but will keep their distance if the family is perceived to be violent, harmful, or unfulfilling. Capricorn have a dry sense of humor and their sarcastic wit is only appreciated by those who find humor everywhere. Highly intellectual, good with numbers and analysis, this sign is not often loud, but they are most definitely the muscle and the power behind the very successful machine. \n HOROSCOPE...While your body experiences calm today, your mind will be working out ideas and solutions to problems. It's going to be a calm and relaxed day for you physically and this will create the perfect conditions for you to be busy mentally. With your body at ease your mind can wander and sort through some important stuff. You will come up with some great ideas and solutions to problems as your brain works on over drive. Share these ideas with others and you can implement them.");
}else if (zs.equalsIgnoreCase("Pisces")) {
	JOptionPane.showMessageDialog(null, "You are...Likeable, energetic, passionate, sensitive. Downside... Because they feel everything so intensely, this sign can often become a clinical worrier. They will worry that they are not worrying. This tendency to worry also leads to indecision on their part, fearing that if they make a decision that others disagree with that they will have upset someone. Pisces don’t like to hurt people’s feelings and as such become conflicted when they have to make decisions. They do not do well as leaders, but are impressive support personnel. Sometimes the have a lack of follow through due to this indecisiveness and require a gentle nudge from other signs to complete tasks on time. \n Upside...Pisces are empathetic people, often feeling badly for someone whose life is not going well. They feel the need to reach out to those who are less fortunate and will often find themselves involved in drama that they hadn’t intended. They are kind, caring individuals who feel everything deeply, even though you would not know it on the surface. They can be creative and imaginative when they believe that they have support to make those leaps. \n HOROSCOPE...You wont work well in groups today and your energy will serve you better if you do things alone. Being in groups and doing things as a team is not going to work well for you today, your energy will serve you much better if you get on with things on your own. If you do have to work as part of a team try to take a smaller role in things, but if possible go it alone for now. Keep your interactions with others to a minimum and you be more productive");
}else if (zs.equalsIgnoreCase("Libra")) {
	JOptionPane.showMessageDialog(null, "You are...Balanced, seeks beauty, sense of justice. Downside...Because Libra take so long to make decisions it can be perceived as laziness, or absent- mindedness. Libra, because of their sense of justice and fair play, will often become argumentative to the exclusion of decorum or appropriateness. Libra don’t like to be in charge, but they like to have a say and to be heard. Upside...Libra all have a sense of fair play about them and become completely upset if they perceive that something is unfair or unjust. They are prone to talking for long periods of time about their favorite subjects. Generally the decisions that a Libra makes are the ones that will benefit the most people. Libra are often self-sacrificing for the good of the team or the family. \n HOROSCOPE...Do not give too much of yourself over to your partner, understand you need to keep a sense of self. You are walking a fine line between romantic happiness and totally losing yourself to your partner. Today, try to come to a place of understanding that you can love your partner just as much while still holding onto a strong sense of self. Giving all of yourself over to the other person is bad for your relationship, and you need a healthy balance of being a couple and being you.");
}else if (zs.equalsIgnoreCase("Gemini")) {
	JOptionPane.showMessageDialog(null, "Cerebral, chatty, loves learning and education, charming, and adventurous. Downside...Gemini like to be the center of attention; always. When they perceive the situation to not be in their favor, they leave it. This can include relationships, careers, and friendships. Because of this need to be seen as important, Gemini will sometimes stretch the truth. When they are focused only on themselves they can be largely unsympathetic and rude. Male Gemini tend to change jobs often, and female Gemini change partners often due to boredom. \n Upside...Gemini are great conversationalists, and are charming people. Interesting to speak with, Gemini know a little bit about a lot of things. They have a great sense of humor and are generally optimistic people. Gemini often make their own fun, despising boredom. HOROSCOPE...Emotional responses to personal tensions today require balance and perspective, and compromise. Any personal or relationship tensions that exist in your life right now will create emotional responses today in you and in others involved. You need to gain better perspective and to bring some balance into whatever is going on. Be ready to compromise to create balance, but do not be walked all over. See things from the other side, but encourage the other person to also do this.");
}else if (zs.equalsIgnoreCase("Virgo")) {
	JOptionPane.showMessageDialog(null, "Particular, logical, practical, sense of duty, critical. Downside...Virgo are particularly attentive to health; theirs, yours, everyone’s, which can often lead to obsessive behaviors toward health (hypochondria). They can also be judgmental and critical of those that they feel are not living up to their potential, or are going about a project in an inefficient way. Virgo are opinionated and have no problem sharing their opinions, even when they should not. \n Upside...Virgo have a heart for their fellow man. They are kind, patient and love to laugh. They are not loud ‘look at me’ signs, but rather prefer to be the strong, silent type. They are creative thinkers and true family oriented people. Male Virgo, once they are committed to relationship never walk away (unless there is a betrayal, and even then it isn’t written in stone). Female Virgo are dedicated parents, often parenting other children in the neighborhood. \n HOROSCOPE... You should spend time with your friends today, as one of them has something important to share with you. Today you should spend time with your friends and be as close to them as possible. One of your friends has something important to share with you, but they may need some encouragement before they feel ready to open up. Do not pressure them, but be there and show that you support them no matter what. Make sure you are paying attention to their mood and behaviour so you are ready to pick up on any problems.");
}else if (zs.equalsIgnoreCase("Cancer")) {
	JOptionPane.showMessageDialog(null, "You are...Emotional, group oriented, seeks security, family. Downside...This sign can be moody, clingy, and often become incredibly insecure if they feel that they are about to lose the friendship or love of someone close to them. If the situation calls for it, they will lie, but often this dishonesty stems from a deep insecurity about being alone. Upside...Cancer have an offbeat sense of humor, often finding something humorous that others don’t. They are extremely good listeners and have a heart for the problems of others. In fact, many gravitate toward this sign because they intuitively know that a Cancer will understand. When a Cancer becomes your friend you can be sure that they are truly your friend and will not consider using someone to their own benefit. Cancer tend to be dependable and reliable. They will tell you anything you want to know about them without blinking an eye as they are drawn to honesty in others as well as themselves. If others recognise all your hard work lately, do not shun the limelight today, you deserve to be noticed. Things are fairly quiet in your house today and it will be a mostly work-focussed day, but if the spotlight does find you, make the most of it. You have worked hard lately and this is no time for being modest and shunning the limelight. You deserve some recognition and if others are noticing you and all you have done, then welcome this and take your moment in the sun ");
}







}
}
